/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pratica04.CI.Gradle_Git;

public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
